### ISSUE TITLE
tag 2.6 - tag added are not on view list

### ISSUE THREAD

**Issue by yalgva** [pluginsGLPI/tag#95] opened 2020-03-12 09:57 UTC
Hello
Thank you for your work !

I installed 2.6 today, it works better than 2.5.
Could you fix this new bug please.

The tag is correctly in the item (appliance plugin or others) but in the view list the tag does not appear.
Thank you for your help

**Comment by stonebuzz** [comment] 2020-03-12 13:46
Hi @yalgva 

I cant reproduce, can you give us more details (screenshot, glpi version, logs ...)

Best regards

**Comment by cedric-anne** [comment] 2020-09-07 06:45
Hi,

We cannot investigate without feedback, I close the issue.

Regards

**Closed by cedric-anne** 2020-09-07 06:45 UTC
Labels: Need feedback, question
